---

- name: install couchdb
  hosts: vagrantgroup
  sudo: yes
  user: root

  pre_tasks:
    - name: install git
      apt: name=git update_cache=yes

  roles:
    - {role: ANXS.build-essential}
    - {role: ANXS.erlang, erlang_version: 17.1, erlang_install_method: "package"}
    - {role: guillaumededrie.couchdb, couchdb_version: 1.6.1}

  tasks:
    - name: create couch admin
      shell: curl -X PUT http://localhost:5984/_config/admins/admin -d '"{{couchdb_admin_password}}"'
      no_log: True
